openapi: 3.0.1
info:
  title: Delivery.Request.Service.Presentation
  version: '1.0'
paths:
  /delivery-request/Search:
    post:
      tags:
        - DeliveryRequest
      parameters:
        - name: Query
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SearchDeliveryRequestQueryResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SearchDeliveryRequestQueryResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SearchDeliveryRequestQueryResponse'
  /delivery-request/Create:
    post:
      tags:
        - DeliveryRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDeliveryRequestCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateDeliveryRequestCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateDeliveryRequestCommand'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CreateDeliveryRequestCommandResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeliveryRequestCommandResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/CreateDeliveryRequestCommandResponse'
  /delivery-request/Cancel:
    post:
      tags:
        - DeliveryRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelDeliveryRequestCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CancelDeliveryRequestCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CancelDeliveryRequestCommand'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /delivery-request/Delete:
    post:
      tags:
        - DeliveryRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteDeliveryRequestCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/DeleteDeliveryRequestCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/DeleteDeliveryRequestCommand'
      responses:
        '204':
          description: No Content
  /delivery-request/Execute:
    post:
      tags:
        - DeliveryRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecuteDeliveryRequestCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/ExecuteDeliveryRequestCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ExecuteDeliveryRequestCommand'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /delivery-request/Update:
    post:
      tags:
        - DeliveryRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDeliveryRequestCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateDeliveryRequestCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateDeliveryRequestCommand'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /delivery-request/SubmitForExecution:
    post:
      tags:
        - DeliveryRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitForExecutionDeliveryRequestCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/SubmitForExecutionDeliveryRequestCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SubmitForExecutionDeliveryRequestCommand'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    CancelDeliveryRequestCommand:
      type: object
      properties:
        id:
          type: string
          format: uuid
        cancellationReason:
          type: string
          nullable: true
      additionalProperties: false
    CreateDeliveryRequestCommand:
      type: object
      properties:
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
      additionalProperties: false
    CreateDeliveryRequestCommandResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
      additionalProperties: false
    DeleteDeliveryRequestCommand:
      type: object
      properties:
        id:
          type: string
          format: uuid
      additionalProperties: false
    DeliveryRequestStatusDto:
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
      type: integer
      format: int32
    ExecuteDeliveryRequestCommand:
      type: object
      properties:
        id:
          type: string
          format: uuid
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
    SearchDeliveryRequestQueryResponse:
      type: object
      properties:
        deliveryRequests:
          type: array
          items:
            $ref: '#/components/schemas/SearchDeliveryRequestQueryResponseDeliveryRequest'
          nullable: true
      additionalProperties: false
    SearchDeliveryRequestQueryResponseDeliveryRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        courierId:
          type: string
          format: uuid
          nullable: true
        status:
          $ref: '#/components/schemas/DeliveryRequestStatusDto'
        cancellationReason:
          type: string
          nullable: true
      additionalProperties: false
    SubmitForExecutionDeliveryRequestCommand:
      type: object
      properties:
        id:
          type: string
          format: uuid
        courierId:
          type: string
          format: uuid
      additionalProperties: false
    UpdateDeliveryRequestCommand:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
      additionalProperties: false